# Generates src/Modifiers.cs from the game's own files, so the modifier messages shown in
# the overlay are exactly what Noita prints. Reads biome_modifiers.lua for each modifier's
# id and translation key, then common.csv for the English text.
$root = Split-Path $PSScriptRoot
$lua  = Get-Content "$root\gamedata\scripts\biome_modifiers.lua" -Raw
$csv  = "C:\Program Files (x86)\Steam\steamapps\common\Noita\data\translations\common.csv"

# English text is the second CSV field. Fields may be quoted and contain commas.
function EnglishOf([string]$line) {
  $i = $line.IndexOf(',')
  if ($i -lt 0) { return $null }
  $rest = $line.Substring($i + 1)
  if ($rest.StartsWith('"')) {
    $sb = New-Object System.Text.StringBuilder
    $k = 1
    while ($k -lt $rest.Length) {
      $ch = $rest[$k]
      if ($ch -eq '"') {
        if ($k + 1 -lt $rest.Length -and $rest[$k + 1] -eq '"') { [void]$sb.Append('"'); $k += 2; continue }
        break
      }
      [void]$sb.Append($ch); $k++
    }
    return $sb.ToString()
  }
  $j = $rest.IndexOf(',')
  if ($j -lt 0) { return $rest }
  return $rest.Substring(0, $j)
}

$text = @{}
foreach ($line in [IO.File]::ReadAllLines($csv, [Text.Encoding]::UTF8)) {
  if ($line -match '^(biomemodifierdesc_[a-z0-9_]+),') { $text[$matches[1]] = EnglishOf $line }
}

# Walk each modifier block in order. A block starts at `id = "..."` and we collect the
# fields the selection logic needs. Blocks inside the biome_modifiers table are the ones
# the weighted pick draws from; the two standalone ones after it are only ever forced.
$tableEnd = -1
$lines = $lua -split "`n"
for ($n = 0; $n -lt $lines.Length; $n++) {
  if ($lines[$n] -match '^biome_modifiers\s*=') { $inTable = $true; continue }
  if ($inTable -and $lines[$n] -match '^\}') { $tableEnd = $n; break }
}
if ($tableEnd -lt 0) { throw "could not find the end of the biome_modifiers table" }

function ListOf([string]$l, [string]$field) {
  if ($l -match "$field\s*=\s*\{([^}]*)\}") {
    return ($matches[1] -split ',' | ForEach-Object { $_.Trim().Trim('"') } | Where-Object { $_ })
  }
  return @()
}

$rows = New-Object System.Collections.ArrayList
$cur = $null
for ($n = 0; $n -lt $lines.Length; $n++) {
  $l = $lines[$n]
  if ($l -match '^\s*id\s*=\s*"([A-Z0-9_]+)"') {
    if ($cur) { $null = $rows.Add($cur) }
    $cur = [ordered]@{ id = $matches[1]; text = $null; p = 0.0; only = @(); skip = @(); flag = ''; inTable = ($n -lt $tableEnd) }
    continue
  }
  if (-not $cur) { continue }
  if ($l -match 'ui_description\s*=\s*"\$?([a-z0-9_]+)"') {
    $cur.text = $text[$matches[1]]
    if (-not $cur.text) { throw "no English text for $($matches[1]) ($($cur.id))" }
  }
  if ($l -match '^\s*probability\s*=\s*([0-9.]+)') { $cur.p = [double]::Parse($matches[1], [Globalization.CultureInfo]::InvariantCulture) }
  if ($l -match 'apply_only_to_biome')     { $cur.only = ListOf $l 'apply_only_to_biome' }
  if ($l -match 'does_not_apply_to_biome') { $cur.skip = ListOf $l 'does_not_apply_to_biome' }
  if ($l -match 'requires_flag\s*=\s*"([a-z0-9_]+)"') { $cur.flag = $matches[1] }
}
if ($cur) { $null = $rows.Add($cur) }

function Lit([string]$s) { '"' + $s.Replace('\','\\').Replace('"','\"') + '"' }
function Arr($a) { if (-not $a -or $a.Count -eq 0) { 'null' } else { 'new[]{ ' + (($a | ForEach-Object { Lit $_ }) -join ', ') + ' }' } }
$inv = [Globalization.CultureInfo]::InvariantCulture
$body = ($rows | ForEach-Object {
  "      new Modifier(" + (Lit $_.id) + ", " + (Lit $_.text) + ", " + $_.p.ToString('R', $inv) + ", " +
  ($(if ($_.inTable) { 'true' } else { 'false' })) + ", " + (Arr $_.only) + ", " + (Arr $_.skip) + ", " +
  ($(if ($_.flag) { Lit $_.flag } else { 'null' })) + "),"
}) -join "`r`n"

$out = @"
// AUTO-GENERATED by tools/gen_modifiers.ps1 from biome_modifiers.lua and common.csv.
// Do not edit by hand: the text must match what the game prints, and the weights and
// rules must match what the game rolls against.
namespace NoitaOverlay {
  internal sealed class Modifier {
    public readonly string Id, Text, RequiresFlag;
    public readonly double Probability;
    public readonly bool InWeightedTable;     // drawn by the weighted pick, or only ever forced
    public readonly string[] OnlyIn, NotIn;
    public Modifier(string id, string text, double p, bool inTable, string[] only, string[] skip, string flag) {
      Id = id; Text = text; Probability = p; InWeightedTable = inTable; OnlyIn = only; NotIn = skip; RequiresFlag = flag;
    }
  }

  internal static class Modifiers {
    /// <summary>In the order biome_modifiers.lua declares them. Order matters for the weighted pick.</summary>
    public static readonly Modifier[] All = {
$body
    };
  }
}
"@
[IO.File]::WriteAllText("$root\src\Modifiers.cs", $out, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "wrote src/Modifiers.cs : $($rows.Count) modifiers"
