# Generates src/BiomeMap.cs : a compact embedded 70x48 biome lookup, no PNG needed at runtime.
Add-Type -AssemblyName System.Drawing
$root = Split-Path $PSScriptRoot
$xml  = [xml](Get-Content "$root\gamedata\biome\_biomes_all.xml" -Raw)
$offsetY = [int]$xml.BiomesToLoad.biome_offset_y
$c2b = @{}
foreach ($b in $xml.BiomesToLoad.Biome) {
  $c = $b.color.ToUpper(); if ($c.Length -eq 8) { $c = $c.Substring(2) }
  if (-not $c2b.ContainsKey($c)) { $c2b[$c] = ($b.biome_filename -replace '^data/biome/','' -replace '\.xml$','') }
}
$bmp = New-Object System.Drawing.Bitmap("$root\gamedata\biome_impl\biome_map.png")
$W = $bmp.Width; $H = $bmp.Height; $offsetX = [int]($W/2)

$names = New-Object System.Collections.ArrayList
$null = $names.Add("")               # index 0 = nothing
$cells = New-Object System.Collections.ArrayList
for ($y=0; $y -lt $H; $y++) {
  for ($x=0; $x -lt $W; $x++) {
    $p = $bmp.GetPixel($x,$y)
    $n = ""
    if ($p.A -ne 0) {
      $k = '{0:X2}{1:X2}{2:X2}' -f $p.R,$p.G,$p.B
      if ($c2b.ContainsKey($k)) { $n = $c2b[$k] }
    }
    $i = $names.IndexOf($n); if ($i -lt 0) { $i = $names.Add($n) }
    if ($i -gt 254) { throw "too many biomes for byte encoding: $i" }
    $null = $cells.Add($i)
  }
}
$bmp.Dispose()

# pack cells as rows of comma-separated bytes, W per line
$lines = @()
for ($y=0; $y -lt $H; $y++) { $lines += (($cells.GetRange($y*$W, $W)) -join ',') }
$nameLits = ($names | ForEach-Object { '"' + $_ + '"' }) -join ','

$out = @"
// AUTO-GENERATED by tools/gen_biomemap.ps1 from Noita's data.wak. Do not edit by hand.
namespace NoitaOverlay {
  internal static class BiomeMap {
    public const int W = $W, H = $H, OffsetX = $offsetX, OffsetY = $offsetY, Chunk = 512;
    static readonly string[] Names = { $nameLits };
    static readonly byte[] Cells = {
      $($lines -join ",`n      ")
    };
    /// <summary>Internal biome id at a world pixel coordinate, or "" if none.</summary>
    public static string At(double worldX, double worldY) {
      int mx = (int)System.Math.Floor(worldX / (double)Chunk) + OffsetX;
      int my = (int)System.Math.Floor(worldY / (double)Chunk) + OffsetY;
      if (mx < 0 || my < 0 || mx >= W || my >= H) return "";
      return Names[Cells[my * W + mx]];
    }
  }
}
"@
Set-Content "$root\src\BiomeMap.cs" $out -Encoding utf8
Write-Host "wrote src/BiomeMap.cs : $($names.Count-1) distinct biomes, ${W}x${H}, offset $offsetX/$offsetY, $($cells.Count) cells"
