// AUTO-GENERATED by tools/gen_modifiers.ps1 from biome_modifiers.lua and common.csv.
// Do not edit by hand: the text must match what the game prints, and the weights and
// rules must match what the game rolls against.
namespace NoitaOverlay {
  internal sealed class Modifier {
    public readonly string Id, Text, RequiresFlag;
    public readonly double Probability;
    public readonly bool InWeightedTable;     // drawn by the weighted pick, or only ever forced
    public readonly string[] OnlyIn, NotIn;
    public Modifier(string id, string text, double p, bool inTable, string[] only, string[] skip, string flag) {
      Id = id; Text = text; Probability = p; InWeightedTable = inTable; OnlyIn = only; NotIn = skip; RequiresFlag = flag;
    }
  }

  internal static class Modifiers {
    /// <summary>In the order biome_modifiers.lua declares them. Order matters for the weighted pick.</summary>
    public static readonly Modifier[] All = {
      new Modifier("MOIST", "The air feels extremely humid", 0.7, true, null, null, null),
      new Modifier("FOG_OF_WAR_REAPPEARS", "A mysterious darkness lingers in this place", 1, true, null, new[]{ "mountain_hall" }, null),
      new Modifier("HIGH_GRAVITY", "The air feels heavy...", 0.5, true, null, null, null),
      new Modifier("LOW_GRAVITY", "The air feels light...", 0.5, true, null, null, null),
      new Modifier("CONDUCTIVE", "The air smells ionized", 0.2, true, null, new[]{ "mountain_hall", "coalmine" }, null),
      new Modifier("FREEZING", "The air feels freezing", 0, true, null, null, null),
      new Modifier("HOT", "The air feels hot", 0.6, true, null, new[]{ "mountain_hall" }, null),
      new Modifier("GOLD_VEIN", "You sense lucrative opportunities", 0.01, true, null, new[]{ "snowcastle" }, null),
      new Modifier("GOLD_VEIN_SUPER", "You sense extremely lucrative opportunities", 0.00025, true, new[]{ "coalmine", "coalmine_alt", "excavationsite", "snowcave" }, null, null),
      new Modifier("PLANT_INFESTED", "It smells like soil after rain", 1, true, null, new[]{ "snowcastle", "snowcave", "rainforest", "rainforest_open", "mountain_hall" }, null),
      new Modifier("FURNISHED", "It feels cozy in here", 0.5, true, null, new[]{ "mountain_hall" }, null),
      new Modifier("BOOBY_TRAPPED", "You feel wary", 0.75, true, null, new[]{ "mountain_hall" }, null),
      new Modifier("PERFORATED", "It feels roomy in here", 0.75, true, null, new[]{ "vault", "vault_frozen", "crypt", "snowcave" }, null),
      new Modifier("SPOOKY", "The hair in the back of your neck stands up", 0.5, true, null, new[]{ "mountain_hall" }, null),
      new Modifier("GRAVITY_FIELDS", "You feel an invisible force pushing and pulling you", 0.3, true, null, new[]{ "mountain_hall" }, null),
      new Modifier("FUNGAL", "The air is filled with fungal spores", 0.5, true, null, new[]{ "mountain_hall", "snowcastle", "snowcave", "fungicave" }, null),
      new Modifier("FLOODED", "Where did all this water come from?", 0.75, true, null, new[]{ "mountain_hall", "rainforest", "rainforest_open", "snowcave", "vault" }, null),
      new Modifier("GAS_FLOODED", "There's a smell of gas in the air", 0.5, true, null, new[]{ "mountain_hall", "excavationsite", "snowcave", "snowcastle", "vault", "crypt" }, null),
      new Modifier("SHIELDED", "This place feels exceptionally secure", 0.1, true, null, new[]{ "mountain_hall", "excavationsite", "snowcave" }, null),
      new Modifier("PROTECTION_FIELDS", "Everything is glowing in a mysterious light...!", 0.2, true, null, new[]{ "mountain_hall" }, "moon_is_sun"),
      new Modifier("OMINOUS", "There's an ominous atmosphere here...!", 0.2, true, null, new[]{ "mountain_hall", "coalmine", "excavationsite" }, "darkmoon_is_darksun"),
      new Modifier("INVISIBILITY", "You suddenly have trouble focusing your eyes...", 0.1, true, null, new[]{ "mountain_hall", "coalmine" }, null),
      new Modifier("WORMY", "You hear creepy crawling everywhere!", 0.05, true, null, new[]{ "mountain_hall", "coalmine" }, null),
      new Modifier("FREEZING_COSMETIC", "The air feels freezing", 0, false, null, null, null),
      new Modifier("FOG_OF_WAR_CLEAR_AT_PLAYER", "It feels gloomy in here", 0, false, null, null, null),
    };
  }
}